kind: Service
apiVersion: v1
metadata:
  name: sonarr
  namespace: sonarr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sonarr.home
spec:
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8989
  type: LoadBalancer
  loadBalancerIP: 192.168.0.206