# Source: prometheus-operator/templates/prometheus-operator/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-operator
  namespace: monitoring # {"$kpt-set":"namespace"}
  labels:
    app: prometheus-operator-operator
    chart: prometheus-operator-9.1.0
    release: "prometheus-operator"
    heritage: "Helm"
spec:
  endpoints:
  - port: http
    honorLabels: true
  selector:
    matchLabels:
      app: prometheus-operator-operator
      release: "prometheus-operator"
  namespaceSelector:
    matchNames:
    - "monitoring" # {"$kpt-set":"namespace"}
