---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brooksby
  namespace: default
  labels:
    app: brooksby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brooksby
  template:
    metadata:
      labels:
        app: brooksby
    spec:
      containers:
      - name: brooksby
        image: starfusionmz/scheduler:latest 
        imagePullPolicy: Always
        env:
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
      volumes:
---
apiVersion: v1
kind: Service
metadata:
  name: brooksby
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: brooksby
    external-dns.alpha.kubernetes.io/hostname: brooksby.home
spec:
  type: ClusterIP
  selector:
    app: brooksby
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brooksby
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: brooksby.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brooksby
            port: 
              number: 80