apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-nfs-ceph-nfs-lb
  namespace: rook-ceph
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.219
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  selector:
    app: rook-ceph-nfs
    ceph_daemon_id: a
    ceph_daemon_type: nfs
    ceph_nfs: ceph-nfs
    instance: a
    nfs: a
    rook_cluster: rook-ceph

