apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-jellyfin
  namespace: plex
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs