# Source: prometheus-operator/templates/grafana/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-grafana
  namespace: monitoring # {"$kpt-set":"namespace"}
  labels:
    app: prometheus-operator-grafana
    chart: prometheus-operator-9.1.0
    release: "prometheus-operator"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: "prometheus-operator"
  namespaceSelector:
    matchNames:
    - "monitoring" # {"$kpt-set":"namespace"}
  endpoints:
  - port: service
    path: "/metrics"
