# Source: prometheus-operator/charts/prometheus-node-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-prometheus-node-exporter
  namespace: monitoring # {"$kpt-set":"namespace"}
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: prometheus-node-exporter
    heritage: Helm
    release: prometheus-operator
    chart: prometheus-node-exporter-1.10.0
    jobLabel: node-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    name: metrics
  selector:
    app: prometheus-node-exporter
    release: prometheus-operator
