# Source: prometheus-operator/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator-prometheus-node-exporter
  namespace: default # {"$kpt-set":"namespace"}
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-1.10.0
    release: "prometheus-operator"
    heritage: "Helm"
imagePullSecrets: []
