nodes:
  - address: gimli.home
    user: gimli
    role:
      - controlplane
      - etcd
      - worker
ingress:
  provider: nginx
  extra_args:
      enable-ssl-passthrough: "true"

kubernetes_version: "v1.19.7-rancher1-1"
