# Source: prometheus-operator/templates/prometheus/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-prometheus-psp
  labels:
    app: prometheus-operator-prometheus
    chart: prometheus-operator-9.1.0
    release: "prometheus-operator"
    heritage: "Helm"
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - prometheus-operator-prometheus
