apiVersion: batch/v1
kind: CronJob
metadata:
  name: ceph-backup
  namespace: default
  labels:
    app: ceph-backup
spec:
  schedule: "0 8 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure        
          nodeSelector:
            kubernetes.io/hostname: lithium.home        
          initContainers:
          - name: init-restic
            image: restic/restic:0.12.1
            command: ['sh', '-c', "restic snapshots > /dev/null || restic init"]
            env:
            - name: RESTIC_PASSWORD
              value: "backup"
            - name: RESTIC_REPOSITORY
              value: "/backups"              
            volumeMounts:
            - name: data
              mountPath: /backups
          containers:
          - name: ceph-backup
            image: restic/restic:0.12.1
            command: ['sh', '-c', "restic --verbose backup /media"]
            env:
            - name: RESTIC_PASSWORD
              value: "backup"      
            - name: RESTIC_REPOSITORY
              value: "/backups"                    
            ports:
            volumeMounts:
            - name: data
              mountPath: /backups
            - name: media
              mountPath: /media 
          volumes:
          - name: data
            hostPath:
              path: /tank/backups
          - name: media
            nfs:
              server: ceph-nfs.home
              path: /cephfs/media          
