apiVersion: batch/v1
kind: CronJob
metadata:
  name: recordings-ageoff
spec:
  schedule: "0 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: recordings-ageoff
            image: busybox
            args:
            - /bin/sh
            - -c
            - find /recordings -mtime +14 -delete
            volumeMounts:
              - name: recordings
                mountPath: /recordings
          volumes:
          - name: recordings
            nfs:
              server: ceph-nfs.home
              path: /cephfs/recordings
          restartPolicy: OnFailure
