---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
  - name: http
    port: 80
    targetPort: 8096
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8920
    protocol: TCP
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: linuxserver/jellyfin:latest 
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        ports:
        - name: http
          containerPort: 8096
          protocol: TCP
        - name: https
          containerPort: 8920
          protocol: TCP
        volumeMounts:
        - name: media
          mountPath: /data
        - name: jellyfin-config
          mountPath: /config
        - name: recordings
          mountPath: /recordings
      volumes:
        - name: media
          nfs:
            server: gimli.home
            path: /media
        - name: jellyfin-config
          nfs: 
            server: gimli.home
            path: /appdata/jellyfin
        - name: recordings
          nfs:
            server: gimli.home
            path: /recordings
---

