
apiVersion: v1
kind: Service
metadata:
  name: logitech-media-server
  namespace: logitech-media-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.207
  selector:
    app: logitech-media-server
  ports:
  - name: ui
    port: 80
    targetPort: 9000
    protocol: TCP
  - name: lms
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: cli
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: squeezebox
    port: 3483
    targetPort: 3483
    protocol: TCP
  - name: chromecast
    port: 49152
    targetPort: 49152
    protocol: TCP
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logitech-media-server
  namespace: logitech-media-server
  labels:
    app: logitech-media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logitech-media-server
  template:
    metadata:
      labels:
        app: logitech-media-server
    spec:
      # hostNetwork: true
      containers:
      - name: logitech-media-server
        image: lmscommunity/logitechmediaserver:latest
        imagePullPolicy: Always
        env:
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        - name: cli
          containerPort: 9090
          protocol: TCP
        - name: squeezebox
          containerPort: 3483
        - name: chromecast
          containerPort: 49152
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /music
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: lms-config
      - name: media
        nfs:
          server: ceph-nfs.home
          path: /cephfs/media/Music