apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-config
  namespace: mqtt
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: rook-cephfs-retain