apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-config
  namespace: bitwarden
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: rook-cephfs-retain