# Source: prometheus-operator/charts/grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-grafana-clusterrolebinding
  labels:
    helm.sh/chart: grafana-5.3.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: "7.0.3"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: prometheus-operator-grafana
  namespace: default # {"$kpt-set":"namespace"}
roleRef:
  kind: ClusterRole
  name: prometheus-operator-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
