# Source: prometheus-operator/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-operator-grafana
  namespace: monitoring # {"$kpt-set":"namespace"}
  labels:
    helm.sh/chart: grafana-5.3.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: "7.0.3"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "cHJvbS1vcGVyYXRvcg=="
  ldap-toml: ""
