# Source: prometheus-operator/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-operator-alertmanager
  namespace: default # {"$kpt-set":"namespace"}
  labels:
    app: prometheus-operator-alertmanager
    chart: prometheus-operator-9.1.0
    release: "prometheus-operator"
    heritage: "Helm"
spec:
  baseImage: quay.io/prometheus/alertmanager
  version: v0.21.0
  replicas: 1
  listenLocal: false
  serviceAccountName: prometheus-operator-alertmanager
  externalUrl: http://prometheus-operator-alertmanager.default:9093
  paused: false
  logFormat: "logfmt"
  logLevel: "info"
  retention: "120h"
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  portName: web
