# Source: prometheus-operator/templates/alertmanager/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-alertmanager
  namespace: monitoring # {"$kpt-set":"namespace"}
  labels:
    app: prometheus-operator-alertmanager
    self-monitor: "true"
    chart: prometheus-operator-9.1.0
    release: "prometheus-operator"
    heritage: "Helm"
spec:
  ports:
  - name: web
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: alertmanager
    alertmanager: prometheus-operator-alertmanager
  type: "ClusterIP"
