network:
    version: 2
    ethernets:
      eno1:
        dhcp4: no
      eno2:
        dhcp4: no
      eno3:
        addresses: [192.168.0.1/24]
        dhcp4: no
        nameservers:
          addresses:
            - 192.168.0.1
          search: [home]
      eno4:
        dhcp4: yes