apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: transmission
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs