apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: radarr-backup-local
  namespace: velero
spec:
  schedule: 0 0 * * *
  template:
    hooks: {}
    includedNamespaces:
    - radarr
    storageLocation: default
    ttl: 120h0m0s
  useOwnerReferencesInBackup: false
