---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller
    external-dns.alpha.kubernetes.io/hostname: unifi-controller.home
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - name: browser-ui
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: http-redir
    port: 8880
    targetPort: 8880
    protocol: TCP
  - name: https-redir
    port: 8843
    targetPort: 8843
    protocol: TCP
  - name: unifi-comms
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: speed-test
    port: 6789
    targetPort: 6789
    protocol: TCP
---
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller
    external-dns.alpha.kubernetes.io/hostname: unifi-controller.home
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - name: dev-discovery
    port: 10001
    targetPort: 10001
    protocol: UDP
  - name: l2-discovery
    port: 1900
    targetPort: 1900
    protocol: UDP
  - name: stun
    port: 3478
    targetPort: 3478
    protocol: UDP
---