apiVersion: v1
kind: Namespace
metadata:
  name: unifi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
      - name: unifi-controller
        image: linuxserver/unifi-controller:latest
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - name: unifi-inform
          containerPort: 8080 # {"$ref":"#/definitions/io.k8s.cli.setters.unifi-inform"}
          protocol: TCP
        - name: browser-ui
          containerPort: 8443
          protocol: TCP
        - name: http-redir
          containerPort: 8880
          protocol: TCP
        - name: https-redir
          containerPort: 8843
          protocol: TCP
        - name: speed-test
          containerPort: 6789
          protocol: TCP
        - name: dev-discovery
          containerPort: 10001
          protocol: UDP
        - name: l2-discovery
          containerPort: 1900
          protocol: UDP
        - name: stun
          containerPort: 3478
          protocol: UDP
        volumeMounts:
        - name: unifi-controller-data
          mountPath: /config
      volumes:
      - name: unifi-controller-data
        hostPath:
          path: /mnt/gv0/appdata/unifi-controller
