---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    # Configure a default setup of Home Assistant (frontend, api, etc)
    default_config:
    frontend:
      themes: !include_dir_merge_named themes

    # Text to speech
    tts:
      - platform: google_translate

    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.0.10
        - 127.0.0.1 
        - 10.43.0.0/16

    homeassistant:
      external_url: "https://home-assistant.lester.network"
      media_dirs:
        media: /media
      time_zone: "US/Eastern"
      currency: USD
      country: US
      latitude: "28.20590646290917"
      longitude: "-82.49559411349301"
