apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: home-assistant
  namespace: monitoring
  labels:
    app: home-assistant
    release: "prometheus-operator"
spec:
  selector:
    matchLabels:
      app: home-assistant
  namespaceSelector:
    matchNames:
    - home-assistant
  endpoints:
  - targetPort: 8123 
    path: /api/prometheus
    bearerTokenSecret:
      name: hass-metrics-token
      key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: hass-metrics-token
  namespace: monitoring
type: Opaque
stringData: 
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI5Yjg5Zjg4MjVlZjc0M2JmOTAzYWFiMDdkMTI2MzRlZiIsImlhdCI6MTYyMjY3ODA2NywiZXhwIjoxOTM4MDM4MDY3fQ.McZPNiSz6BXkQYa3cvMvq2fkGzoXGjkrv32jc22Ji-U