# Source: prometheus-operator/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: prometheus-operator-admission
  labels:
    app: prometheus-operator-admission
    chart: prometheus-operator-9.1.0
    release: "prometheus-operator"
    heritage: "Helm"
webhooks:
- name: prometheusrulemutate.monitoring.coreos.com
  failurePolicy: Ignore
  rules:
  - apiGroups:
    - monitoring.coreos.com
    apiVersions:
    - "*"
    resources:
    - prometheusrules
    operations:
    - CREATE
    - UPDATE
  clientConfig:
    service:
      namespace: monitoring # {"$kpt-set":"namespace"}
      name: prometheus-operator-operator
      path: /admission-prometheusrules/mutate
