apiVersion: v1
kind: Namespace
metadata:
  name: grocy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: grocy
  labels:
    app: grocy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
      - name: grocy
        image: "linuxserver/grocy"
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 9283 # {"$kpt-set":"http-port"}
          protocol: TCP
        env:
        - name: TZ
          value: "America/New_York"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        nfs:
          server: gimli.home
          path: /appdata/grocy
