apiVersion: v1
kind: Service
metadata:
  name: grocy
  namespace: grocy
  annotations:
    metallb.universe.tf/allow-shared-ip: grocy
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9283 # {"$kpt-set":"http-port"}
    protocol: TCP
  selector:
    app: grocy
