('../unifi', 'unifi.deployment.j2')


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-data
  namespace: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller-deployment
  namespace: unifi-controller
  labels:
    app: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller}
    spec:
      containers:
      - name: unifi-controller
        image: linuxserver/unifi-controller:latest 
        env:
        ports:
        - name: unifi-comms
          containerPort: 8080
          protocol: TCP
        - name: browser-ui
          containerPort: 8443          
          protocol: TCP
        - name: http-redir
          containerPort: 8880
          protocol: TCP
        - name: https-redir
          containerPort: 8843
          protocol: TCP
        - name: speed-test
          containerPort: 6789
          protocol: TCP      
        - name: dev-discovery
          containerPort: 10001
          protocol: UDP
        - name: stun-port
          containerPort: 3478
          protocol: UDP        
        volumeMounts:
          - name: unifi-controller-data
            mountPath: /config
      volumes:
        - name: unifi-controller-data
          persistentVolumeClaim:
            claimName: unifi-controller-data
