apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: jackett
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.211
  selector:
    app: jackett
  ports:
  - name: http
    port: 80
    targetPort: 9117
    protocol: TCP
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: jackett
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:latest
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        ports:
        - name: http
          containerPort: 9117
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jackett-config