---
apiVersion: v1
kind: Namespace
metadata:
  name: doods
---
apiVersion: v1
kind: Service
metadata:
  name: doods
  namespace: doods
  annotations:
    metallb.universe.tf/allow-shared-ip: doods
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.210
  selector:
    app: doods
  ports:
  - name: rest
    port: 8080
    targetPort: 8080
    protocol: TCP
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doods
  namespace: doods
  labels:
    app: doods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doods
  template:
    metadata:
      labels:
        app: doods
    spec:
      containers:
      - name: doods
        image: snowzach/doods:cuda
        imagePullPolicy: Always
        resources:
          limits: 
            nvidia.com/gpu: 1
        env:
        - name: TZ
          value: "America/New_York"
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: "NVIDIA_DRIVER_CAPABILITIES"
          value: "compute,video,utility"
        - name: "LOGGER_LEVEL"
          value: "info"
        ports:
        - name: rest
          containerPort: 8080
          protocol: TCP
---

