# Source: prometheus-operator/templates/exporters/kube-scheduler/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-kube-scheduler
  labels:
    app: prometheus-operator-kube-scheduler
    jobLabel: kube-scheduler
    chart: prometheus-operator-9.1.0
    release: "prometheus-operator"
    heritage: "Helm"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
    targetPort: 10251
  selector:
    component: kube-scheduler
  type: ClusterIP
