# Source: prometheus-operator/templates/exporters/kube-proxy/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-kube-proxy
  labels:
    app: prometheus-operator-kube-proxy
    jobLabel: kube-proxy
    chart: prometheus-operator-9.1.0
    release: "prometheus-operator"
    heritage: "Helm"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  selector:
    k8s-app: kube-proxy
  type: ClusterIP
