apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-jellyfin
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: rook-cephfs-retain