#microk8s.helm3 upgrade --install jhub jupyterhub/jupyterhub   --namespace jhub --version=0.8.2 --values jhub.values.yaml --timeout 15m
#microk8s.heml3 uninstall jhub --namespace jhub
singleuser:
    image:
      # Get the latest image tag at:
      # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
      # Inspect the Dockerfile at:
      # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
      name: cschranz/gpu-jupyter
      tag: latest
    #   defaultUrl: "/lab"
    storage:
      dynamic:
        storageClass: local-path

proxy:
  secretToken: `openssl rand -hex 32`

hub:
  db:
    pvc:
      storageClassName: local-path
#   extraConfig:
#     jupyterlab: |
#       c.Spawner.cmd = ['jupyter-labhub']