---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data
  namespace: home-control
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller-deployment
  namespace: home-control
  labels:
    k8s-app: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      name: unifi-controller
      labels:
        app: unifi-controller
    spec:
      hostNetwork: true
      containers:
      - name: unifi-controller
        image: jacobalberty/unifi:latest
        env:
        volumeMounts:
        - name: unifi-config
          mountPath: /unifi
        ports:
        - name: unifi-comms
          containerPort: 8080
          protocol: TCP
        - name: browser-ui
          containerPort: 8443          
          protocol: TCP
        - name: http-redir
          containerPort: 8880
          protocol: TCP
        - name: https-redir
          containerPort: 8843
          protocol: TCP
        - name: speed-test
          containerPort: 6789
          protocol: TCP      
        - name: dev-discovery
          containerPort: 10001
          protocol: UDP
        - name: stun-port
          containerPort: 3478
          protocol: UDP        
      volumes:
      - name: unifi-config
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: nimbus-ceph-fs # name of the filesystem specified in the filesystem CRD.
            clusterNamespace: rook-ceph # namespace where the Rook cluster is deployed
            # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
            # the path must exist on the filesystem, otherwise mounting the filesystem at that path will fail
            path: /apps/unifi-controller