apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    k8s-app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: plex
  template:
    metadata:
      name: plex
      labels:
        k8s-app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:plexpass
        env:
        - name: PLEX_CLAIM
          value: "claim-8p4X5X2sSVwntJLfQn9x"
        - name: TZ
          value: "America/New_York"
        - name: ADVERTISE_IP
          value: "http://100.16.222.247:32400/"
        volumeMounts:
        - name: plex
          mountPath: /config
        - name: media
          mountPath: /data
        - name: transcode
          mountPath: /transcode
        ports:
        - name: plex-server
          containerPort: 32400
          protocol: TCP
        - name: roku
          containerPort: 8324
          protocol: TCP
        - name: plex-control
          containerPort: 3005
          protocol: TCP
        - name: dlna-tcp
          containerPort:  32469
          protocol: TCP
        - name: dlna-udp
          containerPort: 1900
          protocol: UDP      
        - name: avahi
          containerPort: 5353
          protocol: UDP
        - name: gdm1
          containerPort: 32410
          protocol: UDP
        - name: gdm2
          containerPort: 32412
          protocol: UDP                
        - name: gdm3
          containerPort: 32413
          protocol: UDP                
        - name: gdm4
          containerPort: 32414
          protocol: UDP                
      volumes:
      - name: plex
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: nimbus-ceph-fs 
            clusterNamespace: rook-ceph 
            path: /apps/plex/config
      - name: media
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: nimbus-ceph-fs 
            clusterNamespace: rook-ceph 
            path: /media            
      - name: transcode
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: nimbus-ceph-fs 
            clusterNamespace: rook-ceph 
            path: /apps/plex/transcode