apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-config
  namespace: logitech-media-server
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs-retain