apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unms-config
  namespace: unifi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-retain