#helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#helm repo update
#helm install ingress-nginx ingress-nginx/ingress-nginx -f values.yaml
#helm upgrade ingress-nginx ingress-nginx/ingress-nginx -f values.yaml
controller:
  kind: DaemonSet
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    loadBalancerIP: 192.168.0.200
  extraArgs: 
    enable-ssl-passthrough: "true"
    default-ssl-certificate: null