apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |-
    listener 1883
    allow_anonymous true
    socket_domain ipv4
    # listener 9001
    persistence true
    persistence_location /mosquitto/data/
    
    log_timestamp true
    log_timestamp_format %Y-%m-%dT%H:%M:%S
    # log_dest file /mosquitto/log/mosquitto.log
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: mqtt
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.212
  selector:
    app: mqtt
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: mqtt2
    port: 9001
    targetPort: 9001
    protocol: TCP
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: port2
          containerPort: 9001
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /mosquitto/data
        - name: mqtt-conf
          mountPath: /mosquitto/config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mqtt-config
      - name: mqtt-conf
        configMap:
          name: mosquitto-config
          items:
            - key: mosquitto.conf
              path: mosquitto.conf