---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amcrest2mqtt
  namespace: mqtt
  labels:
    app: amcrest2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amcrest2mqtt
  template:
    metadata:
      labels:
        app: amcrest2mqtt
    spec:
      containers:
      - name: amcrest2mqtt
        image: dchesterton/amcrest2mqtt:latest
        imagePullPolicy: Always
        env:
        - name: AMCREST_HOST
          value: "front-door-doorbell"
        - name: AMCREST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: camera-credentials
              key: password                    
        - name: MQTT_HOST
          value: "mqtt.mqtt"
        - name: "MQTT_USERNAME"
          value: ""
        - name: "HOME_ASSISTANT"
          value: "true"
        - name: MQTT_PORT
          value: "1883"
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP