apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: jackett
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-retain