---
apiVersion: v1
kind: Namespace
metadata:
  name: snapcast-server
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapcast-server
  namespace: snapcast-server
  labels:
    app: snapcast-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapcast-server
  template:
    metadata:
      labels:
        app: snapcast-server
    spec:
      containers:
      - name: snapcast-server
        image: leakypixel/snapserver:latest
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - name: stream
          containerPort: 1704
          protocol: TCP         
        - name: tcp-json-rpc
          containerPort: 1705
          protocol: TCP
        - name: http-json-rpc
          containerPort: 1780
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /etc/snapserver.conf
            subPath: snapserver.conf
          - name: data
            mountPath: /var/lib/snapserver
          - name: tmp
            mountPath: /tmp
      - name: snapcast-ui
        image: leakypixel/snapcastr:latest
        imagePullPolicy: Always
        ports:
        - name: ui
          containerPort: 5011
          protocol: TCP
      - name: mopidy
        image: wernight/mopidy
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 6680
          protocol: TCP
        - name: mpd
          containerPort: 6600
          protocol: TCP
        volumeMounts:
           - name: mopidy-conf
             mountPath: /config/mopidy.conf
             subPath: mopidy.conf
           - name: media
             mountPath: /var/lib/mopidy/media
           - name: tmp
             mountPath: /tmp
      volumes:
      - name: data
        nfs:
          server: gimli.home
          path: /appdata/snapcast/
      - name: media
        nfs:
          server: gimli.home
          path: /media/media/Music
      - name: config
        configMap:
          name: snapcast-config
          items:
            - key: snapserver.conf
              path: snapserver.conf
      - name: mopidy-conf
        configMap:
          name: snapcast-config
          items:
            - key: mopidy.conf
              path: mopidy.conf
      - name: tmp
        emptyDir:
          medium: "Memory"
---
