---
apiVersion: v1
kind: Service
metadata:
  name: snapcast-server
  namespace: snapcast-server
  annotations:
    metallb.universe.tf/allow-shared-ip: snapcast-server
spec:
  type: LoadBalancer
  selector:
    app: snapcast-server
  ports:
  - name: stream
    port: 1704
    targetPort: 1704
    protocol: TCP         
  - name: tcp-json-rpc
    port: 1705
    targetPort: 1705
    protocol: TCP
  - name: http-json-rpc
    port: 1780
    targetPort: 1780    
    protocol: TCP
  - name: snap-control-ui
    port: 5011
    targetPort: 5011
    protocol: TCP
  - name: mopidy-ui
    port: 80
    targetPort: 6680
    protocol: TCP    
---