---
# Source: coredns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-coredns
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    helm.sh/chart: "coredns-1.10.1"
    k8s-app: "coredns"
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    app.kubernetes.io/name: coredns
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/instance: "RELEASE-NAME"
    k8s-app: "coredns"
    app.kubernetes.io/name: coredns
  ports:
  - {port: 53, protocol: UDP, name: udp-53}
  - {port: 53, protocol: TCP, name: tcp-53}
  type: ClusterIP
