apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: bitwarden-backup-offsite
  namespace: velero
spec:
  schedule: 0 0 * * *
  template:
    hooks: {}
    includedNamespaces:
    - bitwarden
    storageLocation: glacier
    ttl: 120h0m0s
  useOwnerReferencesInBackup: false
