---
apiVersion: v1
kind: Namespace
metadata:
  name: influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.8.4-alpine
        env:
        - name: USERID
          value: "65534"
        - name: GROUPID
          value: "65534"
        volumeMounts:
        - name: data
          mountPath: /var/lib/influxdb
        ports:
        - name: http
          containerPort: 8086       
          protocol: TCP
      volumes:
      - name: data
        nfs:
          server: gimli.home
          path: /appdata/influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.209
  selector:
    app: influxdb
  ports:
  - name: ui
    port: 80
    targetPort: 8086
    protocol: TCP
---